### ISSUE TITLE
Add Solar Beam to interrupt list

### ISSUE THREAD

**Issue by Nitrak** [Nitrak/Vocal-Raid-Assistant#203] opened 2023-02-01 14:34 UTC
This should already be caught by spell_interrupt, but not when it fails to interrupt?

Investigate.

**Comment by nyy23** [comment] 2023-02-02 19:12
Just tested this ingame.

Actually had to log onto my druid alt - which was an awful experience - and spec into balance -which was an even more awful experience.
Exactly as you wrote: We catch the spell_interrupt event.
If solar beam actually interrupts, this is perfectly handled by the addon. If you cast solar beam without actually interrupting sth, you wont hear the interrupt sound. 

Would close this.

**Comment by nyy23** [comment] 2023-02-05 10:18
Working as intended.

**Comment by Nitrak** [comment] 2023-02-05 18:52
False, it announces if you interrupt your target, but if your silence interrupts a separate monster "Interrupted" is not called.

Example
2 mobs, A and B
A is casting
B is not casting

IF Solar Beam A Then A is interrupted and sound is played.
If Solar Beam B while A is casting Then A is interrupted and no sound is played.

Sound should be played in both instances.

**Comment by Nitrak** [comment] 2023-02-05 19:45
Either we can track SPELL_INTERRUPT and SPELL_CAST_FAILED, but it will also announce interrupts for other sources (Knockback etc) which while it's true can be misleading.

Or we can add a special case to Solar Beam since it's the only ability functioning like this. (This is probably the most "correct", but also ugly thing to do).

Or we can re-add it to the Druid spell-list again.

**Comment by nyy23** [comment] 2023-02-05 21:33
I would say the primary use case for this is to quickly "get an overview" of whether kicks are being used - or not. When Solar Beam "passively" interrupts, we don't necessarily need to play a sound.

**Comment by Nitrak** [comment] 2023-02-06 08:32
I would say, for that exact reason, that we should play a sound when Solar Beam "passively" interrupts because it could just be how someone interrupts if you see the casting target is within range of your active target. The only thing to be mindful of is not screaming out 20 "interrupt" sounds because Solar Beam interrupted 20 spells. We should just output "Interrupt" once.

I agree that we should not announce "interrupt" on every stop-cast (Knockback, Stun, etc).

**Closed** 2024-04-21 00:30 UTC
